apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-vol-claim
spec:
  storageClassName: local-storage
  accessModes:
    -  ReadWriteMany
  resources:
    requests:
      storage: 500Mi