server:
  port: 9081
  
spring:
  application:
    name: fibonacci-app-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.29.16:3306/fibinfo
    url: jdbc:mysql://tan-fib-mysql-service/fibinfo?useSSL=false
    username: tghosh
    password: tghosh
  jpa:
    properties:
      hibernet:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
