server:
  port: 9081
  
spring:
  application:
    name: fibonacci-app-service
  datasource:
    url: jdbc:mysql://192.168.29.16:3306/fibinfo
    username: tghosh
    password: tghosh
  jpa:
    properties:
      hibernet:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
